apiVersion: apps/v1
kind: Deployment
metadata:
  name: snello-k1-deployment
  labels:
    app: snello-k1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: snello-k1
  template:
    metadata:
      labels:
        app: snello-k1
    spec:
      containers:
        - name: snello-k1
          image: snellocms/snello-k1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: snello-k1-service
spec:
  ports:
    - name: http
      targetPort: 8080
      port: 8080
  selector:
    app: snello-k1
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: snello-k1
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
    traefik.enable: true
spec:
  rules:
    - host: k8.flw.ovh
      http:
        paths:
          - path: /snello-k1
            backend:
              serviceName: snello-k1
              servicePort: http
