apiVersion: v1
kind: Service
metadata:
  name: snello-k1
  labels:
    app: snello-k1
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: snello-k1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snello-k1-deployment
  labels:
    app: snello-k1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snello-k1
  template:
    metadata:
      labels:
        app: snello-k1
    spec:
      containers:
        - name: snello-k1
          image: snellocms/snello-k1
          ports:
            - containerPort: 8080
