apiVersion: v1
kind: Service
metadata:
  name: snello-all-in-one
  labels:
    app: snello-all-in-one
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: snello-all-in-one
