on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
       java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml -Pnative -Dquarkus.native.container-runtime=docker
  
    - uses: Azure/docker-login@v1
      with:
        login-server: index.docker.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - run: |
        ls -lah .
        ls -lah target
        docker build -f src/main/docker/Dockerfile.native -t snellocms/snello-k1:${{ github.sha }} .
        docker push snellocms/snello-k1:${{ github.sha }}
      
    - uses: Azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
        
    - uses: Azure/k8s-create-secret@v1
      with:
        container-registry-url: hub.docker.com
        container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
        container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        secret-name: demo-k8s-secret

    - uses: Azure/k8s-deploy@v1
      with:
        manifests: |
          target/kubernetes/kubernetes.yml
        images: |
          snellocms/snello-k1:${{ github.sha }}
        imagepullsecrets: |
          demo-k8s-secret
